path_keywords:
  - attachments
  - backups
  - capabilities
  - cgsnapshots
  - consistencygroups
  - encryption
  - extensions
  - extra_specs
  - get_pools
  - group_snapshots
  - group_specs
  - group_types
  - groups
  - limits
  - manageable_snapshots
  - manageable_volumes
  - members
  - os-hosts
  - os-quota-class-sets
  - os-quota-sets
  - os-volume-transfer
  - os-volume-type-access
  - qos-specs
  - resource_filters
  - snapshots
  - tags
  - types
  - volumes

keyword_exclusions:
  - create_from_src
  - summary
