kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: glance
  labels:
    system: openstack
    type: api
    component: glance
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: glance
  template:
    metadata:
      labels:
        name: glance
      annotations:
        chart-version: {{.Chart.Version}}
        checksum/etc-configmap.conf: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
        checksum/bin-configmap.conf: {{ include (print $.Template.BasePath "/bin-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: glance-api
          securityContext:
            runAsUser: 0
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-glance-api:{{.Values.image_version_glance_api}}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{.Values.global.glance_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          command:
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "glance-api"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "glance-migration"
            - name: DEPENDENCY_SERVICE
              value: "postgres-glance,rabbitmq"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
          ports:
            - name: api
              containerPort: {{.Values.global.glance_api_port_internal}}
          volumeMounts:
            - name: etcglance
              mountPath: /etc/glance
            - name: glance-etc
              mountPath: /etc/glance/glance-api.conf
              subPath: glance-api.conf
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/swift-store.conf
              subPath: swift-store.conf
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/policy.json
              subPath: policy.json
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/glance-api-paste.ini
              subPath: glance-api-paste.ini
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/logging.conf
              subPath: logging.conf
              readOnly: true
            - mountPath: /glance_store
              name: image-store
            - mountPath: /glance-patches
              name: glance-patches
        - name: glance-registry
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-glance-registry:{{.Values.image_version_glance_registry}}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 9191
          command:
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "glance-registry"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "glance"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
          ports:
            - name: registry
              containerPort: 9191
          volumeMounts:
            - name: etcglance
              mountPath: /etc/glance
            - name: glance-etc
              mountPath: /etc/glance/glance-registry.conf
              subPath: glance-registry.conf
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/swift-store.conf
              subPath: swift-store.conf
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/policy.json
              subPath: policy.json
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/glance-registry-paste.ini
              subPath: glance-registry-paste.ini
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/logging.conf
              subPath: logging.conf
              readOnly: true
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.port_metrics}}
      volumes:
        - name: etcglance
          emptyDir: {}
        - name: image-store
          persistentVolumeClaim:
            claimName: glance-pvclaim
        - name: glance-patches
          configMap:
            name: glance-patches
        - name: glance-etc
          configMap:
            name: glance-etc
