kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: metrics-mariadb
  namespace: {{.Release.Namespace}}
  labels:
    system: openstack
    type: database
    component: {{.Values.name}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
   type: Recreate
  selector:
   matchLabels:
    name: metrics-mariadb
  template:
   metadata:
    labels:
     name: metrics-mariadb
   spec:
    containers:
      - name: metrics
        image: "{{ .Values.metrics.image }}:{{ .Values.metrics.imageTag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.metrics.imagePullPolicy | quote }}
        env:
          - name: POSTGRES_PASSWORD
            value: {{.Values.password}}
          - name: DATA_SOURCE_NAME
            value: "login:password@(hostname:port)/"
        ports:
          - name: metrics
            containerPort: {{.Values.port_metrics}}
        {{- if .Values.metrics.customMetrics }}
           args: ["-extend.query-path", "/conf/custom-metrics.yaml"]
        volumeMounts:
          - name: custom-metrics
            mountPath: /conf
            readOnly: true
