# Might we worth building your own ipxe stack here: https://rom-o-matic.eu/
apiVersion: batch/v1
kind: Job
metadata:
  name: ironic-db-migration
  labels:
    system: openstack
    type: job
    component: ironic
spec:
  template:
    metadata:
      annotations:
{{- if and (eq .Capabilities.KubeVersion.Major "1") (lt .Capabilities.KubeVersion.Minor "6") }}
        pod.beta.kubernetes.io/init-containers: '[{
          "name": "kubernetes-entrypoint",
          "image": "{{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-api:{{.Values.image_version_ironic_pxe | default .Values.image_version | required "Please set ironic.image_version or similar"}}",
          "imagePullPolicy": "IfNotPresent",
          "command": ["kubernetes-entrypoint"],
          "env": [{"name": "NAMESPACE", "value": {{ .Release.Namespace | quote }}},
                  {"name": "DEPENDENCY_SERVICE", "value": "postgres-ironic"},
                  {"name": "COMMAND", "value": "true"}]
          }]'
{{- end }}
    spec:
{{- if or (gt .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "6") }}
      initContainers:
      - name: "kubernetes-entrypoint"
        image: "{{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-api:{{.Values.image_version_ironic_pxe | default .Values.image_version | required "Please set ironic.image_version or similar"}}"
        imagePullPolicy: "IfNotPresent"
        command: ["kubernetes-entrypoint"]
        env:
        - name: "NAMESPACE"
          value: {{ .Release.Namespace | quote }}
        - name: "DEPENDENCY_SERVICE"
          value: "postgres-ironic"
        - name: "COMMAND"
          value: "true"
{{- end }}
      restartPolicy: OnFailure
      containers:
      - name: ironic-dbsync
        image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-api:{{.Values.image_version_ironic_pxe | default .Values.image_version | required "Please set ironic.image_version or similar"}}
        imagePullPolicy: IfNotPresent
        command:
        - bash
        args:
        - -c
        - |
          ironic-dbsync upgrade
          true
        env:
        - name: PGAPPNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /etc/ironic
          name: etcironic
        - mountPath: /etc/ironic/ironic.conf
          name: ironic-etc
          subPath: ironic.conf
          readOnly: true
        - mountPath: /etc/ironic/policy.json
          name: ironic-etc
          subPath: policy.json
          readOnly: true
        - mountPath: /etc/ironic/pxe_config.template
          name: ironic-etc
          subPath: pxe_config.template
          readOnly: true
        - mountPath: /etc/ironic/rootwrap.conf
          name: ironic-etc
          subPath: rootwrap.conf
          readOnly: true
        - mountPath: /etc/ironic/logging.ini
          name: ironic-etc
          subPath: logging.ini
          readOnly: true
      volumes:
      - name: etcironic
        emptyDir: {}
      - name: ironic-etc
        configMap:
          name: ironic-etc
          defaultMode: 0444
