{{- if .Values.inspector.ip  }}
kind: Service
apiVersion: v1

metadata:
  name: ironic-inspector
  labels:
    system: openstack
    type: inspector
    component: ironic
spec:
  selector:
    name: ironic-inspector
  ports:
    - name: ironic-inspector
      port: {{.Values.inspector.port_internal}}
  {{- if .Values.inspector.dhcp }}
    - name: dhcp
      protocol: UDP
      port: {{.Values.inspector.dhcp.port}}
    - name: proxy-dhcp
      protocol: UDP
      port: {{.Values.inspector.dhcp.proxy_port}}
    {{- if .Values.inspector.ip }}
  externalIPs:
    - {{.Values.inspector.ip}}
    {{- end }}
  {{- end }}
  sessionAffinity: "ClientIP"
{{- end }}
