kind: Service
apiVersion: v1

metadata:
  name: ironic-inspector
  labels:
    system: openstack
    type: inspector
    component: ironic
spec:
  selector:
    name: ironic-inspector
  ports:
    - name: ironic-inspector
      port: {{.Values.global.ironic_inspector_port_internal}}
    - name: ironic-inspector-dhcp
      protocol: UDP
      port: {{.Values.inspector.dhcp.port}}
  externalIPs:
    - {{.Values.inspector.dhcp.ip}}
  sessionAffinity: "ClientIP"
