apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-patches
  labels:
    system: openstack
    type: patches
    component: ironic
data:
{{ (.Files.Glob "patches/*.patch").AsConfig | indent 4 }}
