kind: Service
apiVersion: v1

metadata:
  name: ironic-pxe
  labels:
    system: openstack
    type: backend
    component: ironic
spec:
  type: NodePort
  selector:
    name: ironic-conductor
  ports:
    - name: ironic-pxe
      protocol: UDP
      port: {{.Values.global.ironic_pxe_port_public}}
  externalIPs:
    - {{.Values.tftp_ip}}
  sessionAffinity: "ClientIP"
