apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: ironic-seed
spec:
  requires:
    - monsoon3/domain-default-seed
    - monsoon3/domain-ccadmin-seed

  roles:
    - cloud_baremetal_admin
    - baremetal_admin
    - baremetal_viewer
    - cloud_compute_admin
    - cloud_network_admin

  services:
  - name: ironic
    type: baremetal
    description: Openstack baremetal provisioning service
 # uncomment once moved to helm-charts
 #    endpoints:
 #    - interface: admin
 #      region: {{ .Values.global.region }}
 #      url: https://{{ include "ironic_api_endpoint_host_public" .}}
 #    - interface: internal
 #      region: {{ .Values.global.region }}
 #      url: http://ironic-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:6385
 #    - interface: public
 #      region: {{ .Values.global.region }}
 #      url: http://ironic-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:6385

  flavors:
    - name: "zh1vic1.small"
      id: "1000"
      vcpus: "8"
      ram: "262144"
      disk: "300"
      description: HANA Baremetal 2 socket 256GB Haswell
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
        "quota:separate": "true"
        "quota:instance_only": "true"
    - name: "zh2vic1.medium"
      id: "1010"
      vcpus: "28"
      ram: "524288"
      disk: "300"
      description: HANA Baremetal 2 socket 512GB Broadwell
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
        "quota:separate": "true"
        "quota:instance_only": "true"
    - name: "zh1mlx1.large"
      id: "1020"
      vcpus: "28"
      ram: "1048576"
      disk: "400"
      description: HANA Baremetal 2 socket 1TB Broadwell
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
        "quota:separate": "true"
        "quota:instance_only": "true"
    - name: "zh1emx1.xlarge"
      id: "1030"
      vcpus: "72"
      ram: "2097152"
      disk: "1228"
      description: HANA Baremetal 4 socket 2TB Haswell
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
        "quota:separate": "true"
        "quota:instance_only": "true"
    - name: "zh2mlx1.xlarge"
      id: "1031"
      vcpus: "88"
      ram: "2097152"
      disk: "400"
      description: HANA Baremetal 4 socket 2TB Broadwell
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
        "quota:separate": "true"
        "quota:instance_only": "true"
    - name: "zh2mlx1.2xlarge"
      id: "1040"
      vcpus: "176"
      ram: "4194304"
      disk: "400"
      description: HANA Baremetal 8 socket 4TB Broadwell
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
        "quota:separate": "true"
        "quota:instance_only": "true"
    - name: "zh2mlx1.3xlarge"
      id: "1050"
      vcpus: "176"
      ram: "6291456"
      disk: "400"
      description: HANA Baremetal 8 socket 6TB Broadwell
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
        "quota:separate": "true"
        "quota:instance_only": "true"

  domains:
  - name: Default
    users:
    - name: {{ .Values.global.ironic_service_user }}{{ .Values.global.user_suffix }}
      description: Ironic Service
      password: {{ .Values.global.ironic_service_password | default (tuple . .Values.global.ironic_service_user | include "identity.password_for_user") | quote }}
      roles:
      - project: service
        role: service
      - project: service
        role: cloud_network_admin
      - project: service
        role: cloud_compute_admin
      - project: service
        role: cloud_baremetal_admin
      - project: service
        role: swiftreseller
  - name: ccadmin
    projects:
    - name: master
      roles:
      - user: image-build@Default
        role: cloud_baremetal_admin
    groups:
    - name: CCADMIN_CLOUD_ADMINS
      roles:
      - project: master
        role: cloud_baremetal_admin
      - project: cloud_admin
        role: cloud_baremetal_admin
