apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-etc
  labels:
    system: openstack
    type: configuration
    component: cinder

data:
  api-paste.ini: |
{{ include (print $.Template.BasePath "/etc/_api-paste.ini.tpl") . | indent 4 }}
  cinder.conf: |
{{ include (print $.Template.BasePath "/etc/_cinder.conf.tpl") . | indent 4 }}
  rootwrap.conf: |
{{ include (print .Template.BasePath "/etc/_rootwrap.conf.tpl") . | indent 4 }}
  policy.json: |
{{ include (print $.Template.BasePath "/etc/_cinder-policy.json.tpl") . | indent 4 }}
{{- if .Values.audit.enabled }}
  cinder_audit_map.yaml: |
{{ include (print .Template.BasePath "/etc/_cinder_audit_map.yaml.tpl") . | indent 4 }}
{{- end }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
