kind: Service
apiVersion: v1

metadata:
  name: designate-api
  labels:
    system: openstack
    type: api
    component: designate
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{.Values.global.designate_metrics_port}}"
spec:
  type: NodePort
  selector:
    app: designate-api
  ports:
    - name: designate-api
      port: {{.Values.global.designate_api_port_internal}}
