kind: Service
apiVersion: v1

metadata:
  name: designate-mdns
  labels:
    system: openstack
    type: backend
    component: designate

spec:
  type: NodePort
  selector:
    app: designate-mdns
  ports:
    - name: designate-mdns-tcp
      protocol: TCP
      port: {{.Values.global.designate_mdns_port_public}} 
    - name: designate-mdns-udp
      protocol: UDP
      port: {{.Values.global.designate_mdns_port_public}}
  externalIPs: 
    - {{.Values.global.designate_mdns_external_ip}}
