apiVersion: batch/v1
kind: Job
metadata:
  name: designate-migration
  labels:
    system: openstack
    type: configuration
    component: designate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: designate-migration
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-designate-central-m3:{{.Values.image_version_designate_central_m3}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/db-migrate"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "designate-mariadb"
          volumeMounts:
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin
