apiVersion: batch/v1
kind: Job
metadata:
  name: designate-pools
  labels:
    system: openstack
    type: configuration
    component: designate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name:  designate-pools
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-designate-pool-manager:{{.Values.image_version_designate_pool_manager}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "/container.init/manage-pools"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "designate-migration"
            - name: DEPENDENCY_SERVICE
              value: "designate-mariadb,rabbitmq"
          volumeMounts:
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin
            defaultMode: 0755