# Default values for mariadb.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: DEFINED-IN-COMPONENT-CHART
image: mariadb:10.1
port_public: 3306
#
#root_password:
#initdb_configmap:
#persistance_claim:

metrics:
  enabled: false
  image: prom/mysqld-exporter
  imageTag: v0.1.1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
