# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  rabbitmq_default_user: openstack
  rabbitmq_admin_user: admin
  rabbitmq_metrics_user: monitoring
  rabbitmq_port_public: '5672'
  rabbitmq_port_management: '15672'
  rabbitmq_port_metrics: '9150'

  rabbitmq_default_pass: null
  rabbitmq_admin_pass: null
  rabbitmq_metrics_pass: null
  rabbit_transient_queues_ttl: 1800
  user_suffix: ""

rabbit_rpc:
  persistence:
    enabled: true
