apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: nova-console
  labels:
    system: openstack
    type: backend
    component: nova
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.vice_president }}
    vice-president: "true"
    {{- end }}
spec:
  tls:
     - secretName: tls-{{include "nova_console_endpoint_host_public" . | replace "." "-" }}
       hosts: [{{include "nova_console_endpoint_host_public" .}}]
  rules:
    - host: {{include "nova_console_endpoint_host_public" .}}
      http:
        paths:
        - path: /novnc
          backend:
            serviceName: nova-console
            servicePort: novnc
        - path: /spicehtml5
          backend:
            serviceName: nova-console
            servicePort: spicehtml5
        - path: /serial
          backend:
            serviceName: nova-console
            servicePort: serial
