
{{- define "fernet" -}}
{{- range $i, $secret := .Values.fernet_secrets -}}
{{  $i }}: {{ $secret | println }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: fernet-secret
  labels:
    system: openstack
    component: nova
  annotations:
    max_active_keys: '3'
data:
{{ include "fernet" . | indent 4 }}
