apiVersion: batch/v1
kind: Job
metadata:
  name: nova-migration
  labels:
    system: openstack
    type: configuration
    component: nova
spec:
  template:
    metadata:
      annotations:
        configmap-bin-hash: {{ include (print $.Template.BasePath "/bin-configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: nova-migration
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-api:{{.Values.image_version_nova_api | default .Values.image_version | required "Please set nova.image_version or similar" }}
          imagePullPolicy: IfNotPresent
          command:
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "/container.init/db-migrate"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "postgres-nova"
            - name: PGAPPNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /etc/nova
              name: etcnova
            - mountPath: /etc/nova/nova.conf
              name: nova-etc
              subPath: nova.conf
              readOnly: true
            - mountPath: /etc/nova/nova-api.conf
              name: nova-etc
              subPath: nova-api.conf
              readOnly: true
            - mountPath: /etc/nova/api-paste.ini
              name: nova-etc
              subPath: api-paste.ini
              readOnly: true
{{- if .Values.audit.enabled }}
            - mountPath: /etc/nova/nova_audit_map.yaml
              name: nova-etc
              subPath: nova_audit_map.yaml
              readOnly: true
{{- end }}
            - mountPath: /etc/nova/policy.json
              name: nova-etc
              subPath: policy.json
              readOnly: true
            - mountPath: /etc/nova/logging.ini
              name: nova-etc
              subPath: logging.ini
              readOnly: true
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: etcnova
          emptyDir: {}
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: container-init
          configMap:
            name: nova-bin
            defaultMode: 0755
