apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: nova-seed
spec:
  requires:
  - monsoon3/domain-default-seed
  - monsoon3/domain-cc3test-seed
  - monsoon3/domain-ccadmin-seed
  - monsoon3/domain-bs-seed
  - monsoon3/domain-fsn-seed
  - monsoon3/domain-hcm-seed
  - monsoon3/domain-hcp03-seed
  - monsoon3/domain-hec-seed
  - monsoon3/domain-monsoon3-seed
  - monsoon3/domain-s4-seed
  - monsoon3/domain-wbs-seed

  roles:
  - compute_admin
  - compute_viewer
  - cloud_compute_admin
  - cloud_network_admin

  services:
  - name: nova
    type: compute
    description: Openstack Compute
    endpoints:
      # Trailing slash is important, otherwise there will be a redirect to http url with slash, even if https terminated
    - interface: admin
      region: '{{.Values.global.region}}'
      url: '{{.Values.global.nova_api_endpoint_protocol_admin}}://{{include "nova_api_endpoint_host_admin" .}}:{{.Values.global.nova_api_port_admin}}/v2.1/'
    - interface: internal
      region: '{{.Values.global.region}}'
      url: '{{.Values.global.nova_api_endpoint_protocol_internal}}://{{include "nova_api_endpoint_host_internal" .}}:{{.Values.global.nova_api_port_internal}}/v2.1/'
    - interface: public
      region: '{{.Values.global.region}}'
      url: '{{.Values.global.nova_api_endpoint_protocol_public}}://{{include "nova_api_endpoint_host_public" .}}:{{.Values.global.nova_api_port_public}}/v2.1/'
  - name: nova_legacy
    type: compute_legacy
    description: Openstack Compute Legacy Service
    endpoints:
    - interface: admin
      region: '{{ .Values.global.region }}'
      url: '{{.Values.global.nova_api_endpoint_protocol_admin}}://{{include "nova_api_endpoint_host_admin" .}}:{{.Values.global.nova_api_port_admin}}/v2/%(tenant_id)s'
    - interface: internal
      region: '{{ .Values.global.region }}'
      url: '{{.Values.global.nova_api_endpoint_protocol_internal}}://{{include "nova_api_endpoint_host_internal" .}}:{{.Values.global.nova_api_port_internal}}/v2/%(tenant_id)s'
    - interface: public
      region: '{{ .Values.global.region }}'
      url: '{{.Values.global.nova_api_endpoint_protocol_public}}://{{include "nova_api_endpoint_host_public" .}}:{{.Values.global.nova_api_port_public}}/v2/%(tenant_id)s'

  domains:
  - name: Default
    users:
    - name: admin
      roles:
      - domain: Default
        role: cloud_compute_admin
      - project: admin
        role: cloud_compute_admin
    - name: {{ .Values.global.nova_service_user }}{{ .Values.global.user_suffix | default "" }}
      description: Nova Service
      password: {{ .Values.global.nova_service_password | default (tuple . .Values.global.nova_service_user | include "identity.password_for_user") | quote }}
      roles:
      - project: service
        role: service
      - project: service
        role: admin
      - project: service
        role: cloud_network_admin
      - project: service
        role: cloud_compute_admin
    - name: nova_nanny{{ .Values.global.user_suffix | default "" }}
      description: Nova Nanny
      password: {{ tuple . "nova_nanny" | include "identity.password_for_user" | quote }}
    groups:
    - name: administrators
      roles:
      - domain: Default
        role: cloud_compute_admin
      - project: admin
        role: cloud_compute_admin

  - name: ccadmin
    projects:
    - name: cloud_admin
      roles:
      - user: admin@Default
        role: cloud_compute_admin
      # permission to enumerate all projects and domains
      - user: nova_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: admin
      # permission to manage all ressources checked by the nanny
      - user: nova_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: cloud_compute_admin
      - user: nova_nanny{{ .Values.global.user_suffix | default "" }}@Default
        role: cloud_volume_admin
    groups:
    - name: CCADMIN_CLOUD_ADMINS
      roles:
      - project: cloud_admin
        role: cloud_compute_admin
    - name: CCADMIN_API_SUPPORT
      roles:
       - project: api_support
         role: compute_admin
       - project: api_tools
         role: compute_admin
       - domain: ccadmin
         role: compute_admin
         inherited: true
    - name: CCADMIN_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - project: compute_tools
        role: compute_admin
      - domain: ccadmin
        role: compute_admin
        inherited: true
    - name: CCADMIN_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - project: network_tools
        role: compute_admin
      - domain: ccadmin
        role: compute_viewer
        inherited: true
    - name: CCADMIN_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - project: storage_tools
        role: compute_admin
      - domain: ccadmin
        role: compute_viewer
        inherited: true
    - name: CCADMIN_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: ccadmin
        role: compute_viewer
        inherited: true

  - name: bs
    groups:
    - name: BS_API_SUPPORT
      roles:
      - project: api_support
        role: compute_admin
      - domain: bs
        role: compute_admin
        inherited: true
    - name: BS_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - domain: bs
        role: compute_admin
        inherited: true
    - name: BS_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - domain: bs
        role: compute_viewer
        inherited: true
    - name: BS_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - domain: bs
        role: compute_viewer
        inherited: true
    - name: BS_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: bs
        role: compute_viewer
        inherited: true

  - name: fsn
    groups:
    - name: FSN_API_SUPPORT
      roles:
      - project: api_support
        role: compute_admin
      - domain: fsn
        role: compute_admin
        inherited: true
    - name: FSN_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - domain: fsn
        role: compute_admin
        inherited: true
    - name: FSN_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - domain: fsn
        role: compute_viewer
        inherited: true
    - name: FSN_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - domain: fsn
        role: compute_viewer
        inherited: true
    - name: FSN_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: fsn
        role: compute_viewer
        inherited: true

  - name: hcm
    groups:
    - name: HCM_API_SUPPORT
      roles:
      - project: api_support
        role: compute_admin
      - domain: hcm
        role: compute_admin
        inherited: true
    - name: HCM_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - domain: hcm
        role: compute_admin
        inherited: true
    - name: HCM_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - domain: hcm
        role: compute_viewer
        inherited: true
    - name: HCM_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - domain: hcm
        role: compute_viewer
        inherited: true
    - name: HCM_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: hcm
        role: compute_viewer
        inherited: true

  - name: hcp03
    groups:
    - name: HCP03_API_SUPPORT
      roles:
      - project: api_support
        role: compute_admin
      - domain: hcp03
        role: compute_admin
        inherited: true
    - name: HCP03_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - domain: hcp03
        role: compute_admin
        inherited: true
    - name: HCP03_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - domain: hcp03
        role: compute_viewer
        inherited: true
    - name: HCP03_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - domain: hcp03
        role: compute_viewer
        inherited: true
    - name: HCP03_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: hcp03
        role: compute_viewer
        inherited: true

  - name: hec
    groups:
    - name: HEC_API_SUPPORT
      roles:
      - project: api_support
        role: compute_admin
      - domain: hec
        role: compute_admin
        inherited: true
    - name: HEC_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - domain: hec
        role: compute_admin
        inherited: true
    - name: HEC_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - domain: hec
        role: compute_viewer
        inherited: true
    - name: HEC_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - domain: hec
        role: compute_viewer
        inherited: true
    - name: HEC_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: hec
        role: compute_viewer
        inherited: true

  - name: monsoon3
    groups:
    - name: MONSOON3_DOMAIN_ADMINS
      roles:
      - project: cc-demo
        role: compute_admin
    - name: MONSOON3_API_SUPPORT
      roles:
      - project: api_support
        role: compute_admin
      - domain: monsoon3
        role: compute_admin
        inherited: true
    - name: MONSOON3_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - domain: monsoon3
        role: compute_admin
        inherited: true
    - name: MONSOON3_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - domain: monsoon3
        role: compute_viewer
        inherited: true
    - name: MONSOON3_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - domain: monsoon3
        role: compute_viewer
        inherited: true
    - name: MONSOON3_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: monsoon3
        role: compute_viewer
        inherited: true

  - name: s4
    groups:
    - name: S4_API_SUPPORT
      roles:
      - project: api_support
        role: compute_admin
      - domain: s4
        role: compute_admin
        inherited: true
    - name: S4_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - domain: s4
        role: compute_admin
        inherited: true
    - name: S4_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - domain: s4
        role: compute_viewer
        inherited: true
    - name: S4_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - domain: s4
        role: compute_viewer
        inherited: true
    - name: S4_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: s4
        role: compute_viewer
        inherited: true

  - name: wbs
    groups:
    - name: WBS_API_SUPPORT
      roles:
      - project: api_support
        role: compute_admin
      - domain: wbs
        role: compute_admin
        inherited: true
    - name: WBS_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: compute_admin
      - domain: wbs
        role: compute_admin
        inherited: true
    - name: WBS_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: compute_admin
      - domain: wbs
        role: compute_viewer
        inherited: true
    - name: WBS_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: compute_admin
      - domain: wbs
        role: compute_viewer
        inherited: true
    - name: WBS_SERVICE_DESK
      roles:
      - project: service_desk
        role: compute_admin
      - domain: wbs
        role: compute_viewer
        inherited: true
