kind: Service
apiVersion: v1

metadata:
  name: nova-vmware-vspc
  labels:
    system: openstack
    type: backend
    component: nova
spec:
   selector:
   name: nova-vmware-vspc
   ports:
     - name: proxy
       port: 13370
       targetPort: proxy
    - name: admin
      port: 13371 
       targetPort: admin
  externalIPs: ["10.44.11.151"]
