apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-backup-{{.Values.name}}
  labels:
    system: openstack
    type: configuration
    component: database

data:
  postgres.backup.full: {{ .Values.backup.interval_full }}
  postgres.backup.incr: {{ .Values.backup.interval_incr }}
