apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-bin-{{.Values.name}}
  labels:
    system: openstack
    type: configuration
    component: database

data:
  pgbouncer-start: |
{{ .Files.Get "bin/pgbouncer-start" | indent 4 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}
