apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-etc-{{.Values.name}}
  labels:
    system: openstack
    type: configuration
    component: database

data:
  postgresql.conf: |
{{ tuple "etc/_postgresql.conf.tpl" . | include "template" | indent 4 }}
  pg-hba.conf: |
{{ tuple "etc/_pg_hba.conf.tpl" . | include "template" | indent 4 }}
{{- if .Values.exporter }}
  queries.yaml: |
{{ toYaml .Values.exporter | indent 4}}
{{- end }}
