apiVersion: v1
kind: Secret
metadata:
  name: mariadb-{{.Values.name}}
  labels:
    system: openstack
    type: database
    component: mariadb-{{.Values.name}}
type: Opaque
data:
  root-password: {{ default "" .Values.root_password | b64enc | quote }}
