{{- if not .Values.rabbitmq }}
kind: Service
apiVersion: v1

metadata:
  name: rabbitmq
  labels:
    system: openstack
    component: messaging
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{.Values.global.rabbitmq_port_metrics}}"
spec:
  selector:
    app: neutron-rabbitmq

  ports:
    - name: public
      port: {{ .Values.global.rabbitmq_port_public }}
    - name: management
      port: {{ .Values.global.rabbitmq_port_management }}
  {{- if .Values.global.rabbitmq_external_ip }}
  externalIPs:
    - {{.Values.global.rabbitmq_external_ip}}
  {{- end }}
{{- end }}
